// tag::DE[]
== Erläuterungen zur Beispielprüfung Certified Professional for Software Architecture - Foundation Level (CPSA-F(R))

Die vorliegende Prüfung ist eine Beispielprüfung, welche in Form und Umfang an die Zertifizierungsprüfung des Certified Professional for Software Architecture - Foundation Level (CPSA-F®) angelehnt ist. Sie dient der Veranschaulichung der echten iSAQB® CPSA®-Prüfung sowie der entsprechenden Prüfungsvorbereitung.

Die Beispielprüfung besteht aus 39 Multiple-Choice-Fragen, welche je nach Schwierigkeitsgrad mit 1 bis 2 Punkten bewertet werden können. Es müssen zum Bestehen der Prüfung mindestens 60 Prozent erreicht werden. In dieser Probeprüfung können 50,0 Punkte erreicht werden, zum Bestehen wären 30,0 Punkte erforderlich.

Grundsätzlich gilt: richtige Antworten ergeben Pluspunkte, falsche Antworten führen zu Punktabzug, jedoch nur in Bezug auf die jeweilige Frage. Führt die falsche Beantwortung einer Frage zu einem negativen Punktergebnis, so wird diese Frage mit insgesamt 0 Punkten bewertet.
Die Multiple-Choice-Fragen der Beispielprüfung gliedern sich in drei Arten von Fragen:

**A-Fragen (Einfachauswahlfragen, „Auswahl”):**
Wählen Sie zu einer Frage aus der Liste von Antwortmöglichkeiten die einzig korrekte Antwort aus. Es gibt nur eine korrekte Antwort. Sie erhalten die angegebene Punktzahl für das Ankreuzen der korrekten Antwort. Die erreichbare Punktzahl beträgt je nach Schwierigkeitsgrad 1-2 Punkte.

**P-Fragen (Mehrfachauswahlfragen, „Pick“):**
Wählen Sie zu einer Frage aus der Liste von Antwortmöglichkeiten die im Text vorgegebene Anzahl von korrekten Antworten aus. Kreuzen Sie maximal so viele Antworten an, wie im Einleitungstext verlangt werden. Sie erhalten für jede korrekte Antwort anteilig 1/n der Gesamtpunkte. Für jedes nicht-korrekte Kreuz wird 1/n der Punkte abgezogen. Die Punktzahl beträgt je nach Schwierigkeitsgrad 1-2 Punkte.

**K-Fragen (Klärungsfragen, „Kreuz“):**
Wählen Sie zu einer Frage die korrekte der beiden Optionen zu jeder Antwortmöglichkeit aus („richtig“ oder „falsch“ bzw. „zutreffend“ oder „nicht zutreffend“). Sie erhalten für jedes korrekt gesetzte Kreuz anteilig 1/n der Punkte. Nicht korrekt gesetzte Kreuze führen zum Abzug von 1/n der Punkte. Wird in einer Zeile KEINE Antwort ausgewählt, so gibt es weder Punkte noch Abzüge. Die Punktzahl beträgt je nach Schwierigkeitsgrad 1-2 Punkte.

Zur genaueren Erläuterung der Fragetypen und Punkteverteilung stehen weitere Informationen unter der Prüfungsregeln des CPSA-F zur Verfügung.

Die Bearbeitungsdauer beträgt 75 Minuten für Muttersprachler und 90 Minuten für Nicht- Muttersprachler. Um eine möglichst authentische Prüfungsvorbereitung zu gewährleisten, sollte die Bearbeitungszeit eingehalten sowie auf jegliche Hilfsmittel (wie Seminarunterlagen, Bücher, Internet etc.) verzichtet werden.

Im Anschluss erfolgt die Auswertung der Prüfung mit Hilfe der Musterlösung.
Sofern der iSAQB® e.V. als Quelle und Copyright-Inhaber angegeben wird, darf die vorliegende Beispielprüfung im Rahmen von Schulungen eingesetzt, zur Prüfungsvorbereitung genutzt oder unentgeltlich weitergegeben werden. 

Es ist ausdrücklich untersagt, diese Prüfungsfragen in einer echten Prüfung zu verwenden.

// end::DE[]

// tag::EN[]
== Introduction: General information about the iSAQB Advanced Level
// end::EN[]

